mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

dns:
  enable: true
  ipv6: true
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "time.*.com"
    - "ntp.*.com"
    - "dns.msftncsi.com"
    - "www.msftncsi.com"
    - "www.msftconnecttest.com"
    - "localhost.ptlogin2.qq.com"
  nameserver:
    - tls://223.5.5.5:853
    - tls://120.53.53.53:853
  proxy-server-nameserver:
    - tls://223.5.5.5:853
    - tls://120.53.53.53:853
  nameserver-policy:
    "geosite:cn,private":
      - tls://223.5.5.5:853
      - tls://120.53.53.53:853
    "geosite:geolocation-!cn":
      - tls://1.0.0.1:853
      - tls://8.8.8.8:853